# Generated by Django 3.2.4 on 2021-06-11 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewEng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('review_author', models.CharField(blank=True, max_length=100)),
                ('review_pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentEng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(default=' ')),
                ('comment_author', models.CharField(blank=True, max_length=100)),
                ('comment_pub_date', models.DateField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_eng.revieweng')),
            ],
        ),
    ]
