# Generated by Django 3.2.4 on 2021-06-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_rus', '0002_commentrus_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrus',
            name='comment_text',
            field=models.TextField(default=' '),
        ),
    ]
